---
# =============================================
time-interval: 120 # Default: 120 (2 Minuts)
# 60 = 1 Minute
# =============================================
message-reset-all: "&aAll mines were successfully restarted."
# =============================================
...
